version: "3"

services:
  api:
    build: .
    command: bash -c "uvicorn service.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
